kind: pipeline
  name: my-small-satellite pipeline

  steps:
    - name: test
        image: maven:3-jdk-11
        commands:
          - mvn clean test package

    - name: send telegram notification
        image: appleboy/drone-telegram
        settings:
          token: 986857118:AAFN9uAhYl_0WMYUE6hWGPoLArjjBBPxDnM
          to: 733452136